export const PERMISSIONS = [
  { code: "org:manage", description: "Manage organization settings" },
  { code: "users:read", description: "View users" },
  { code: "users:write", description: "Create and update users" },
  { code: "users:assign_roles", description: "Assign roles to users" },
  { code: "roles:manage", description: "Manage roles and permissions" },
  { code: "leads:read", description: "View leads" },
  { code: "leads:write", description: "Create and update leads" },
  { code: "leads:delete", description: "Delete leads" },
  { code: "leads:assign", description: "Assign lead ownership" },
  { code: "contacts:read", description: "View contacts" },
  { code: "contacts:write", description: "Create and update contacts" },
  { code: "contacts:delete", description: "Delete contacts" },
  { code: "contacts:assign", description: "Assign contact ownership" },
  { code: "companies:read", description: "View companies" },
  { code: "companies:write", description: "Create and update companies" },
  { code: "companies:delete", description: "Delete companies" },
  { code: "companies:assign", description: "Assign company ownership" },
  { code: "opportunities:read", description: "View opportunities" },
  { code: "opportunities:write", description: "Create and update opportunities" },
  { code: "opportunities:delete", description: "Delete opportunities" },
  { code: "opportunities:approve", description: "Approve opportunity stage changes" },
  { code: "events:read", description: "View events" },
  { code: "events:write", description: "Create and update events" },
  { code: "events:delete", description: "Delete events" },
  { code: "automations:read", description: "View automations" },
  { code: "automations:write", description: "Create and update automations" },
  { code: "automations:run", description: "Run automations" },
  { code: "audit:read", description: "View audit logs" },
  { code: "extension:capture", description: "Capture leads via extension" },
  { code: "extension:match", description: "Match Gmail/email to CRM records" },
  { code: "settings:manage", description: "Manage workspace settings and API keys" },
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number]["code"];

export const ROLE_TEMPLATES: Record<string, PermissionCode[]> = {
  Admin: PERMISSIONS.map((p) => p.code),
  Manager: [
    "users:read",
    "leads:read",
    "leads:write",
    "leads:assign",
    "contacts:read",
    "contacts:write",
    "contacts:assign",
    "companies:read",
    "companies:write",
    "companies:assign",
    "opportunities:read",
    "opportunities:write",
    "opportunities:approve",
    "events:read",
    "events:write",
    "automations:read",
    "automations:write",
    "automations:run",
    "audit:read",
    "extension:capture",
    "extension:match",
  ],
  Rep: [
    "leads:read",
    "leads:write",
    "contacts:read",
    "contacts:write",
    "companies:read",
    "companies:write",
    "opportunities:read",
    "opportunities:write",
    "events:read",
    "events:write",
    "automations:read",
    "extension:capture",
    "extension:match",
  ],
  Viewer: [
    "leads:read",
    "contacts:read",
    "companies:read",
    "opportunities:read",
    "events:read",
    "automations:read",
    "audit:read",
  ],
};
